version: '3'
services:
  web:
    image: pm/web
    build: ./server
    volumes:
      - ./server/web/:/src/
    ports:
      - "8080:8080"
    links:
      - redis
  gunicorn:
    image: pm/gunicorn
    build: ./server/gunicorn
    volumes:
      - ./server/engine/:/src/
    ports:
      - "8000:8000"
    links:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    hostname: "redis"
  